# NumPy Searching Arrays
---

## Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

---

In [1]:
# Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [2]:
# Find the indexes where the values are odd:

import numpy as np

arr = np.array([10, 14, 93, 41, 8, 7])

x = np.where(arr%2 == 1)

print(x)

(array([2, 3, 5]),)



---
# Search Sorted

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

---

In [3]:
# Find the indexes where the value 7 should be inserted:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


---
# Search From the Right Side

By default the left most index is returned, but we can give side='right' to return the right most index instead.

---


In [4]:
# Find the indexes where the value 7 should be inserted, starting from the right:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


---

# Multiple Values

To search for more than one value, use an array with the specified values.

---

In [7]:
# Find the indexes where the values 2, 4, 6, and 8 should be inserted:

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6, 8])

print(x)

[1 2 3 4]
